"""
Rebalancing date generation for the factor backtest engine.

Produces business-day-aligned end-of-period dates so portfolios are never
rebalanced on a weekend or market holiday.  Three frequencies are supported:

  monthly   — last business day of each calendar month
  quarterly — last business day of each calendar quarter (Mar/Jun/Sep/Dec)
  annual    — last business day of each calendar year (December)

All dates are generated by pandas, which handles month-end, quarter-end, and
year-end alignment automatically.  Dates before start_date or after end_date
are excluded, so the caller always receives a clean, bounded list.
"""

from typing import List

import pandas as pd


_FREQ_MAP = {
    "monthly":   pd.offsets.BusinessMonthEnd(),
    "quarterly": pd.offsets.BQuarterEnd(),
    "annual":    pd.offsets.BYearEnd(),
}


def get_rebalance_dates(
    start_date: str,
    end_date: str,
    frequency: str,
) -> List[pd.Timestamp]:
    """
    Generate a list of rebalancing dates between start_date and end_date.

    Rebalancing occurs on the last business day of each period.  The start_date
    is used as the anchor; the first rebalance date on or after start_date is
    included, and dates up to and including end_date are returned.

    Simplifying assumption: rebalancing can happen on any business day in the
    period even if the exchange is closed (e.g., certain national holidays not
    captured by the BusinessMonthEnd calendar).  Production systems would use
    a market calendar (e.g., NYSE via pandas_market_calendars).

    Parameters
    ----------
    start_date : str
        Inclusive start date, 'YYYY-MM-DD'.
    end_date : str
        Inclusive end date, 'YYYY-MM-DD'.
    frequency : str
        One of 'monthly', 'quarterly', or 'annual'.

    Returns
    -------
    list[pd.Timestamp]
        Rebalancing dates, sorted ascending.

    Raises
    ------
    ValueError
        If frequency is not one of the supported values.
    """
    if frequency not in _FREQ_MAP:
        raise ValueError(
            f"Unsupported frequency '{frequency}'. "
            f"Choose from: {list(_FREQ_MAP.keys())}"
        )

    freq = _FREQ_MAP[frequency]
    dates = pd.date_range(start=start_date, end=end_date, freq=freq)
    return list(dates)
